# ML pipline

# Read  --> Split  --> Divide --> Train  --> Predict  --> Evaluate

In [144]:
import numpy as np
import pandas as pd

data ={
    "area":[100, 1550, 200, 250,300],
    "bedroom":[2,3, 3, 4, 5],
    "age":[20, 15,10, 15, 2],
    "price":[200, 300, 400, 500, 650]
}

df = pd.DataFrame(data)
df.to_csv("housing.csv", index=False)

In [145]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Step 1: Read

In [146]:
df=pd.read_csv("housing.csv")
df.head()

   area  bedroom  age  price
0   100        2   20    200
1  1550        3   15    300
2   200        3   10    400
3   250        4   15    500
4   300        5    2    650

# Step 2: Separate features and the label

In [147]:
X = df[["area", "bedroom", "age"]]
y = df["price"]

# Step 3: Split the data

In [148]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.4)

# Step 4: Train model
## 4.1: Create model
## 4.2: Fit model

In [149]:
model = LinearRegression()

In [150]:
model.fit(x_train, y_train)

LinearRegression()

# Step 5: Predict

In [151]:
y_pred = model.predict(x_test)

# Step 6: Evaluate

In [152]:
from sklearn.metrics import r2_score

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("RMSE: ", rmse)

mse = mean_squared_error(y_test, y_pred)
print("MSE: ", mean_squared_error(y_test, y_pred))

r2=r2_score(y_test, y_pred)
print("R2: ", r2)

RMSE:  481.13582990836744
MSE:  231491.6868216135
R2:  -13.815467956583264

In [153]:
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("RMSE: ", rmse)

mse = mean_squared_error(y_test, y_pred)
print("MSE: ", mean_squared_error(y_test, y_pred))

r2=r2_score(y_test, y_pred)
print("R2: ", r2)

RMSE:  481.13582990836744
MSE:  231491.6868216135
R2:  -13.815467956583264

# ML pipline for linear class

In [154]:
import numpy as np
import pandas as pd

data ={
    "hours_studied":[2, 3, 4, 5,6],
    "attendance":[50,60, 70, 80, 90],
    "passed":[0, 0, 0, 1, 1],
}

df = pd.DataFrame(data)
df.to_csv("sudents.csv", index=False)

In [155]:
df=pd.read_csv("sudents.csv")
df.head()

   hours_studied  attendance  passed
0              2          50       0
1              3          60       0
2              4          70       0
3              5          80       1
4              6          90       1

In [156]:
X = df[["hours_studied", "attendance"]]
y = df["passed"]

In [157]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.4, stratify=y)

In [158]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [159]:
model.fit(x_train, y_train)

LogisticRegression()

In [160]:
y_pred = model.predict(x_test)

In [161]:
from sklearn.metrics  import accuracy_score, precision_score, recall_score, f1_score
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1_score = f1_score(y_test, y_pred)
print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1 Score: ", f1_score)

Accuracy:  1.0
Precision:  1.0
Recall:  1.0
F1 Score:  1.0